Create data model
blase147/Firmtecs_blog pull request #1
Opened 2023-02-02 09:15 UTC by blase147

## In this project;
- I created a data model for firmtecs_blog

2023-02-02 09:20 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @blase147,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You do not have a descriptive README. Kindly add and format your README using [the Microverse template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-02 09:31 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @blase147,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that does not have a README. I think you may want to look at the file name. It should be `README.md`, not `README .md` (notice the space after "E")

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-02 09:51 UTC, DammyShittu requested changes
Hi @blase147,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 09:51 UTC, DammyShittu commented on README.md
- [ ] You have not implemented any of the migrations needed for this project.

  ![ireo](https://user-images.githubusercontent.com/54848363/216291192-58509eab-a9bf-414c-a655-be98d4be532d.jpg)

  Kindly follow the needed lessons and run the migrations for generating the different models: `User`, `Post`, `Comment`, and `Like`. The tables should have the columns shared with you in the ERD diagram.

2023-02-06 12:03 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @blase147,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-06 12:03 UTC, omar-muhamad commented on db/migrate/20230206111817_add_user_to_coments.rb
> +  end
- [ ] you have a typo error you wrote `:coments` instead of `comments`, So please fix that.
- [ ] This reference is adding a foreign key between the comments table and the author table, not the users table as expected, please fix that.
[hint] you can fix it like that:
```ruby
add_reference :comments, :author, foreign_key: { to_table: :users }, null: false
```

2023-02-06 12:03 UTC, omar-muhamad commented on db/migrate/20230206111913_add_user_ref_to_likes.rb
> +  end
- [ ] Same here, Please make this reference between the likes table and users table as `author_id`, So it will be like that:
```ruby
add_reference :likes, :author, foreign_key: { to_table: :users }, null: false
```

2023-02-06 12:03 UTC, omar-muhamad commented on db/migrate/20230206112115_add_user_ref_to_posts.rb
> +  end
- [ ] Same here, Please make this reference between the posts table and users table as `author_id`, So it will be like that:
```ruby
add_reference :posts, :author, foreign_key: { to_table: :users }, null: false
```

- [ ] After editing the migrations I mentioned, Please run these migrations using this command `rails db:migrate` so rails can create the schema file for your database.

2023-02-06 12:48 UTC, blase147 commented on db/migrate/20230206112115_add_user_ref_to_posts.rb
> +  end
Hello @Omar-Muhamad. Thanks for your feedback. However, I am a little bit confused here. Do I need to apply the changes manually, if not what code do I run to create this "**add_reference :posts, :author, foreign_key: { to_table: :users }, null: false**"?

2023-02-06 12:52 UTC, Omar-Muhamad commented on db/migrate/20230206112115_add_user_ref_to_posts.rb
> +  end
> Hello @Omar-Muhamad. Thanks for your feedback. However, I am a little bit confused here. Do I need to apply the changes manually, if not what code do I run to create this "**add_reference :posts, :author, foreign_key: { to_table: :users }, null: false**"?

Yes you can edit the migrations yourself.

2023-02-06 13:25 UTC, blase147 commented on db/migrate/20230206112115_add_user_ref_to_posts.rb
> +  end
Thanks

2023-02-07 07:09 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 07:52 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
### Please kindly update the changes suggested in the README file it's mark optional because the previous reviewer miss it there are all mandatory changes

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 07:52 UTC, CollinsTatang commented on README.md
> +  <br/>
### **Optional**

- [ ] Please delete the microverse logo from your REAME file.

2023-02-07 07:52 UTC, CollinsTatang commented on README.md
> +
### **Optional**
- [ ] Please add section for `Key Features` on your [README](https://github.com/microverseinc/readme-template) file

2023-02-07 07:52 UTC, CollinsTatang commented on README.md
> +
### **Optional**

- [ ] Please add section for `Future Features` in your [README](https://github.com/microverseinc/readme-template) file.

2023-02-07 07:52 UTC, CollinsTatang commented on README.md
> +
### **Optional**

- [ ] Please add section for `Acknowledgments` to your [README](https://github.com/microverseinc/readme-template)

2023-02-07 07:52 UTC, CollinsTatang commented on README.md
> +This project is [MIT](./LICENSE) licensed.
### **Optional**
- [ ] Please fix the link to your LICENSE file is broken.

2023-02-07 08:47 UTC, merged