Blog app: add authorization rules
blase147/Firmtecs_blog pull request #12
Opened 2023-02-22 11:13 UTC by blase147

In this PR, I:

- Installed CanCanCan in your project.
- Added a `role` column to the users table using a migration 
- A user can delete a post if it is theirs or if they have an admin role (column `role` has value `"admin"`). Used CanCanCan for this authorization.
    - For that, I implemented the post-deleting functionality. Added the "Delete" button to the view and ensured that only authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column `role` has value `"admin"`). Used CanCanCan for this authorization.
    - For that, I implemented the comment-deleting functionality. Added the "Delete" button to the view and ensured that only authorized users can see it.
    
  ## Please note: I don't have a coding partner this week

2023-02-22 13:03 UTC, OLIPLICHE requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Linter is green (the last commit has a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used 👏

## Required Changes ♻️
- [ ] I would advise you to add a `role` column to the `user's table` and remember to use migration for this. It is part of the project requirement.
- [ ] Here is what I am getting in trying to sign up. 
![Capture](https://user-images.githubusercontent.com/63972670/220626676-28ad68d4-7787-4bd3-91f6-60b3a9fb0fc7.JPG)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 14:02 UTC, Reem-lab requested changes
# Hi @blase147, 👋🏻👋🏻 

Great work on making the changes requested by a previous reviewer 👏 🤩💯💯✨✨
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

 ## Highlights ✨
- No Linters erros 💯
- Followed Gitflow ✅
- Great working on the fuctionality ✅
- Descriptive PR 💯


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 14:02 UTC, Reem-lab commented on app/models/user.rb
> +  end
- kudos for creating  user.admin? method inside the user model. Great job 🔥🙏🏻💯✨

2023-02-22 14:02 UTC, Reem-lab commented on app/models/user.rb
> +  validates :PostsCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
- [ ] I think you still have an error when I try to sign up but when I checked where is the problem i think it is here he can't see PostsCounter defined but when I tryied to comment it out it works 🤩✨ so please check this problem and try to solve it ✨✅

- The same error this before I comment this line ⬇⬇
![image](https://user-images.githubusercontent.com/58553711/220640594-3bf2354b-5c71-40c4-9388-20e3e2c8cd01.png)



- [ ] Even though I solved that problem bu commenting the two lines for validation but I still can't sign up totally, i didn't recevie any mail for confimation my e-mail 🙏🏻💯✨

## The two lines
![image](https://user-images.githubusercontent.com/58553711/220641223-7ae761e4-f35a-42ef-8f12-daccb1be7bb0.png)

## The error 💯💯
![image](https://user-images.githubusercontent.com/58553711/220640018-3834c754-eef4-45a6-b175-b79c3bd2511d.png)

2023-02-22 14:02 UTC, Reem-lab commented on app/models/user.rb
>    validates :name, presence: true
- [ ] I think this also made a problem because you don't have any input while siging up to add a name so you can add an input to the name in the sign up views or just delete this validation because it is prevent the user from signing up ✅✨💯🙏🏻

- This line validation the name also give errors ♻♻
![image](https://user-images.githubusercontent.com/58553711/220640843-7b29f624-6071-4f73-b056-c59d2d8de72b.png)

2023-02-23 08:12 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @blase147, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean and Organized code

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 10:10 UTC, merged