Blog app - add forms
blase147/Firmtecs_blog pull request #7
Opened 2023-02-14 09:25 UTC by blase147

In this project I;

- Created a method called current_user in my ApplicationController to make current user data available to all controllers.
    - It returns the first user from the database.
- Created forms to perform the following functions:
    - Create a Post on behalf of the current_user 
    - Create a comment on behalf of the current_user 
- Allowed Users to add likes to Posts.

2023-02-14 11:17 UTC, mckent05 requested changes
Hi @blase147, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 11:17 UTC, mckent05 commented on app/controllers/comments_controller.rb
> +        redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
- Good job done so far, but this does not redirect to the user_post_path` when a new comment is created, please fix this 🙏

2023-02-14 11:17 UTC, mckent05 commented on app/controllers/posts_controller.rb
> +        redirect_to user_posts_path(current_user)
- According to the project requirements, when a new post is created it should redirect to the `user_post_path`, this is not so in your project, please fix this 🙏

2023-02-14 11:56 UTC, gemmen29 requested changes
Hi @blase147, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Highlights💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 11:56 UTC, gemmen29 commented on app/controllers/comments_controller.rb
> +  load_and_authorize_resource
- [ ] Kindly remove the `load_and_authorize_resource` as it causes an error when I try to create a new comment.

2023-02-15 08:26 UTC, FrederickMih approved these changes
## Hi 🙋 @blase147   , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights <img src = "https://media.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif" width='30' ></img>


- PR is professional ✔️ 
- Routing works as expected ✔️ 
- Linters checks passed ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 15:41 UTC, merged