Blog app - integration specs for views and fix n+1 problems
blase147/Firmtecs_blog pull request #8
Opened 2023-02-20 11:41 UTC by blase147

In this PR, I did the following:

Solved N+1 problem when fetching all posts and their comments for a user without using the bullet gem

Used Capybara to write integration tests for each view of the Blog App project according to the requirements

Implemented tests for user index page
Implemented tests for user show page
Implemented tests for post index page
Implemented tests for post show page

2023-02-20 12:46 UTC, rotimiazeez requested changes
# Hi @blase147 👍🏽,
## Good job so far!
### To Highlight 👇🏽
- No Linter error ✔️ 
- Good PR description 👍🏽 
- Good commit message(s) 😉
- Descriptive README 📖
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag (@rotimiazeez) me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-02-20 12:46 UTC, rotimiazeez commented on spec/integration/post_show_spec.rb
> +end
- Please note that the post-show specs are currently failing. Kindly make sure all your tests are passing to pass this milestone 😉 
![Screenshot from 2023-02-20 13-36-59](https://user-images.githubusercontent.com/44624138/220110513-7cecc8c1-bdcd-4c7c-a104-b9e0d92a1394.png)

2023-02-20 12:46 UTC, rotimiazeez commented on spec/integration/user_show_spec.rb
> +end
- Please note that the user-show specs are currently failing. Kindly make sure all your tests are passing to pass this milestone 😉 
![Screenshot from 2023-02-20 13-41-36](https://user-images.githubusercontent.com/44624138/220111622-bce13a18-c6c0-49bf-8df8-210bbc8b3b81.png)

2023-02-20 12:46 UTC, rotimiazeez commented on spec/integration/user_index_spec.rb
> +end
- Please note that the user-index specs are currently failing. Kindly make sure all your tests are passing to pass this milestone 😉 
![Screenshot from 2023-02-20 13-44-33](https://user-images.githubusercontent.com/44624138/220111985-1f3c2624-8833-40bb-be4f-02e965c0493a.png)

2023-02-21 11:05 UTC, sumairq approved these changes
### Hi @blase147 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 11:16 UTC, merged